### ISSUE TITLE
option `hard_wrap` is already used

### ISSUE THREAD

**Issue by aneeshdurg** [barryclark/jekyll-now#1918]
using the latest version of `github-pages` (`222`), I observe the following backtrace when running `jekyll build`. Is a specific version of `github-pages` needed?

```
Configuration file: /home/aneesh/jekyll-now/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /home/aneesh/jekyll-now
       Destination: /home/aneesh/jekyll-now/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
/usr/lib/ruby/vendor_ruby/kramdown/options.rb:36: warning: already initialized constant Kramdown::Options::Definition
/home/aneesh/gems/gems/kramdown-2.3.1/lib/kramdown/options.rb:36: warning: previous definition of Definition was here
/usr/lib/ruby/vendor_ruby/kramdown/options.rb:39: warning: already initialized constant Kramdown::Options::ALLOWED_TYPES
/home/aneesh/gems/gems/kramdown-2.3.1/lib/kramdown/options.rb:39: warning: previous definition of ALLOWED_TYPES was here
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2014-3-3-Hello-World.md':
                    Option name hard_wrap is already used
jekyll 3.9.0 | Error:  Option name hard_wrap is already used
Traceback (most recent call last):
        36: from /home/aneesh/gems/bin/jekyll:23:in `<main>'
        35: from /home/aneesh/gems/bin/jekyll:23:in `load'
        34: from /home/aneesh/gems/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        33: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        32: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        31: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        30: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        29: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        28: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        27: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
        26: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
        25: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
        24: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:71:in `process'
        23: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:191:in `render'
        22: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:462:in `render_docs'
        21: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:462:in `each_value'
        20: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:463:in `block in render_docs'
        19: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:463:in `each'
        18: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
        17: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:479:in `render_regenerated'
        16: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:62:in `run'
        15: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:83:in `render_document'
        14: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `convert'
        13: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `reduce'
        12: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `each'
        11: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:101:in `block in convert'
        10: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:76:in `convert'
         9: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:12:in `setup'
         8: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:34:in `get_processor'
         7: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:34:in `new'
         6: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown/kramdown_parser.rb:21:in `initialize'
         5: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown/kramdown_parser.rb:57:in `load_dependencies'
         4: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
         3: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `each'
         2: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
         1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- kramdown-parser-gfm (LoadError)
        45: from /home/aneesh/gems/bin/jekyll:23:in `<main>'
        44: from /home/aneesh/gems/bin/jekyll:23:in `load'
        43: from /home/aneesh/gems/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
        42: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        41: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        40: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        39: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        38: from /usr/share/rubygems-integration/all/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        37: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        36: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
        35: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
        34: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
        33: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:71:in `process'
        32: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:191:in `render'
        31: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:462:in `render_docs'
        30: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:462:in `each_value'
        29: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:463:in `block in render_docs'
        28: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:463:in `each'
        27: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
        26: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:479:in `render_regenerated'
        25: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:62:in `run'
        24: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:83:in `render_document'
        23: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `convert'
        22: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `reduce'
        21: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `each'
        20: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:101:in `block in convert'
        19: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:76:in `convert'
        18: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:12:in `setup'
        17: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:34:in `get_processor'
        16: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown.rb:34:in `new'
        15: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown/kramdown_parser.rb:21:in `initialize'
        14: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/converters/markdown/kramdown_parser.rb:57:in `load_dependencies'
        13: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
        12: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/external.rb:55:in `each'
        11: from /home/aneesh/gems/gems/jekyll-3.9.0/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
        10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
         9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
         8: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
         7: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown-parser-gfm.rb:10:in `<top (required)>'
         6: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown-parser-gfm.rb:10:in `require_relative'
         5: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm.rb:13:in `<top (required)>'
         4: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm.rb:13:in `require_relative'
         3: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm/options.rb:10:in `<top (required)>'
         2: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm/options.rb:11:in `<module:Kramdown>'
         1: from /home/aneesh/gems/gems/kramdown-parser-gfm-1.1.0/lib/kramdown/parser/gfm/options.rb:13:in `<module:Options>'
/usr/lib/ruby/vendor_ruby/kramdown/options.rb:52:in `define': Option name hard_wrap is already used (ArgumentError)
```

**Comment by aneeshdurg** [comment]
Using the most recent jekyll version seems to have been working for a while.
