### ISSUE TITLE
`jekyll serve`  not working in my Fedora 36 LXDE laptop

### ISSUE THREAD

**Issue by sohang3112** [barryclark/jekyll-now#2006]
Console Output of `jekyll serve` was:

```
Configuration file: none
            Source: /home/sohang/My Blog
       Destination: /home/sohang/My Blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout 'post' requested in sohang3112.github.io/_posts/2014-3-3-Hello-World.md does not exist.
     Build Warning: Layout 'page' requested in sohang3112.github.io/404.md does not exist.
     Build Warning: Layout 'page' requested in sohang3112.github.io/about.md does not exist.
     Build Warning: Layout 'default' requested in sohang3112.github.io/index.html does not exist.
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'sohang3112.github.io/style.scss':
                    File to import not found or unreadable: reset. on line 5
jekyll 3.9.2 | Error:  File to import not found or unreadable: reset. on line 5
/home/sohang/.local/share/gem/ruby/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': File to import not found or unreadable: reset. on line 5 (Jekyll::Converters::Scss::SyntaxError)
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:118:in `convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:101:in `block in convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `reduce'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:83:in `render_document'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /home/sohang/bin/jekyll:25:in `load'
	from /home/sohang/bin/jekyll:25:in `<main>'
(sass):5: File to import not found or unreadable: reset. (Sass::SyntaxError)
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:67:in `rescue in import'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:44:in `import'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:101:in `block in convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `reduce'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:83:in `render_document'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /home/sohang/bin/jekyll:25:in `load'
	from /home/sohang/bin/jekyll:25:in `<main>'
/home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:65:in `import': File to import not found or unreadable: reset. (Sass::SyntaxError)
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:101:in `block in convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `reduce'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:99:in `convert'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:83:in `render_document'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/sohang/.local/share/gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/sohang/.local/share/gem/ruby/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /home/sohang/bin/jekyll:25:in `load'
	from /home/sohang/bin/jekyll:25:in `<main>'
```

Assignees: sohang3112
Labels: bug

**Comment by sohang3112** [comment]
I forked this repository and was following the instructions for locally installing in `README.md`. The above error occured when I did `jekyll serve` in the project directory, after succesfully doing `gem install github-pages`.

**Comment by sohang3112** [comment]
@barryclark Do you have any idea why this error could be occurring and how to fix it?

**Comment by sohang3112** [comment]
@barryclark Any idea how to fix this error??
